name: Backend Tests

on:
  push:
    branches: [feature/test-branch-protection,main]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    # TODO : Setup Python 3.11 avec cache pip
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip' # caching pip dependencies
    # TODO : Installez UV avec pip
    - name: Installez UV
      run: pip install uv
    # TODO : Installez les dépendances (cd backend && uv sync)
    - name: Installez dépendances
      run: |
        cd backend
        uv sync
    # TODO : Lancez les tests
    - name: Mon étape
      run: |
        cd backend/
        uv run pytest -v --cov
        

